/* Generated by build.py — do not edit by hand. */
const CACHE_NAME = "mba-s4-notes-a5dc6db3a4ba";
const PRECACHE = [
  "index.html",
  "offline.html",
  "404.html",
  "manifest.json",
  "assets/css/style.css",
  "assets/js/nav.js",
  "assets/icons/icon-192.png",
  "assets/icons/icon-512.png",
  "assets/icons/icon-maskable-512.png",
  "assets/icons/apple-touch-icon.png",
  "assets/icons/icon.svg",
  "assets/vendor/katex/katex.min.css",
  "assets/vendor/katex/katex.min.js",
  "assets/vendor/katex/contrib/auto-render.min.js",
  "assets/vendor/katex/fonts/KaTeX_AMS-Regular.woff2",
  "assets/vendor/katex/fonts/KaTeX_Caligraphic-Bold.woff2",
  "assets/vendor/katex/fonts/KaTeX_Caligraphic-Regular.woff2",
  "assets/vendor/katex/fonts/KaTeX_Fraktur-Bold.woff2",
  "assets/vendor/katex/fonts/KaTeX_Fraktur-Regular.woff2",
  "assets/vendor/katex/fonts/KaTeX_Main-Bold.woff2",
  "assets/vendor/katex/fonts/KaTeX_Main-BoldItalic.woff2",
  "assets/vendor/katex/fonts/KaTeX_Main-Italic.woff2",
  "assets/vendor/katex/fonts/KaTeX_Main-Regular.woff2",
  "assets/vendor/katex/fonts/KaTeX_Math-BoldItalic.woff2",
  "assets/vendor/katex/fonts/KaTeX_Math-Italic.woff2",
  "assets/vendor/katex/fonts/KaTeX_SansSerif-Bold.woff2",
  "assets/vendor/katex/fonts/KaTeX_SansSerif-Italic.woff2",
  "assets/vendor/katex/fonts/KaTeX_SansSerif-Regular.woff2",
  "assets/vendor/katex/fonts/KaTeX_Script-Regular.woff2",
  "assets/vendor/katex/fonts/KaTeX_Size1-Regular.woff2",
  "assets/vendor/katex/fonts/KaTeX_Size2-Regular.woff2",
  "assets/vendor/katex/fonts/KaTeX_Size3-Regular.woff2",
  "assets/vendor/katex/fonts/KaTeX_Size4-Regular.woff2",
  "assets/vendor/katex/fonts/KaTeX_Typewriter-Regular.woff2",
  "adv-ml/index.html",
  "adv-ml/week-1.html",
  "adv-ml/week-2.html",
  "adv-ml/week-3.html",
  "adv-ml/week-4.html",
  "adv-ml/week-5.html",
  "adv-ml/week-6.html",
  "adv-ml/week-7.html",
  "adv-ml/week-8.html",
  "adv-ml/week-9.html",
  "adv-ml/week-10.html",
  "adv-ml/week-11.html",
  "adv-ml/week-12.html",
  "adv-ml/week-13.html",
  "adv-ml/week-14.html",
  "adv-ml/week-15.html",
  "csr/index.html",
  "csr/week-1.html",
  "csr/week-2.html",
  "csr/week-3.html",
  "csr/week-4.html",
  "csr/week-5.html",
  "csr/week-6.html",
  "csr/week-7.html",
  "csr/week-8.html",
  "csr/week-9.html",
  "csr/week-10.html",
  "csr/week-11.html",
  "csr/week-12.html",
  "csr/week-13.html",
  "csr/week-14.html",
  "csr/week-15.html",
  "dl/index.html",
  "dl/week-1.html",
  "dl/week-2.html",
  "dl/week-3.html",
  "dl/week-4.html",
  "dl/week-5.html",
  "dl/week-6.html",
  "dl/week-7.html",
  "dl/week-8.html",
  "dl/week-9.html",
  "dl/week-10.html",
  "dl/week-11.html",
  "dl/week-12.html",
  "dl/week-13.html",
  "dl/week-14.html",
  "dl/week-15.html",
  "efl/index.html",
  "efl/week-1.html",
  "efl/week-2.html",
  "efl/week-3.html",
  "efl/week-4.html",
  "efl/week-5.html",
  "entrepreneurship/index.html",
  "entrepreneurship/week-1.html",
  "entrepreneurship/week-2.html",
  "entrepreneurship/week-3.html",
  "entrepreneurship/week-4.html",
  "entrepreneurship/week-5.html",
  "entrepreneurship/week-6.html",
  "entrepreneurship/week-7.html",
  "entrepreneurship/week-8.html",
  "entrepreneurship/week-9.html",
  "entrepreneurship/week-10.html",
  "entrepreneurship/week-11.html",
  "entrepreneurship/week-12.html",
  "entrepreneurship/week-13.html",
  "entrepreneurship/week-14.html",
  "entrepreneurship/week-15.html",
  "nlp/index.html",
  "nlp/week-1.html",
  "nlp/week-2.html",
  "nlp/week-3.html",
  "nlp/week-4.html",
  "nlp/week-5.html",
  "nlp/week-6.html",
  "nlp/week-7.html",
  "nlp/week-8.html",
  "nlp/week-9.html",
  "nlp/week-10.html",
  "nlp/week-11.html",
  "nlp/week-12.html",
  "nlp/week-13.html",
  "nlp/week-14.html",
  "nlp/week-15.html",
  "project/index.html",
  "project/week-1.html",
  "project/week-2.html",
  "project/week-3.html",
  "project/week-4.html",
  "project/week-5.html",
  "project/week-6.html",
  "project/week-7.html",
  "project/week-8.html",
  "project/week-9.html",
  "project/week-10.html",
  "project/week-11.html",
  "project/week-12.html",
  "project/week-13.html",
  "project/week-14.html",
  "project/week-15.html",
  "visualization/index.html",
  "visualization/week-1.html",
  "visualization/week-2.html",
  "visualization/week-3.html",
  "visualization/week-4.html",
  "visualization/week-5.html",
  "visualization/week-6.html",
  "visualization/week-7.html",
  "visualization/week-8.html",
  "visualization/week-9.html",
  "visualization/week-10.html",
  "visualization/week-11.html",
  "visualization/week-12.html",
  "visualization/week-13.html",
  "visualization/week-14.html",
  "visualization/week-15.html"
];

function inScope(url) {
  return url.startsWith(self.registration.scope);
}

function assetURL(path) {
  return new URL(path, self.registration.scope).href;
}

async function cacheAll(cache) {
  const batch = 20;
  for (let i = 0; i < PRECACHE.length; i += batch) {
    const slice = PRECACHE.slice(i, i + batch);
    await Promise.all(slice.map(async (path) => {
      const href = assetURL(path);
      try {
        const request = new Request(href, { cache: "reload", mode: "same-origin" });
        const response = await fetch(request);
        if (!response || !response.ok) throw new Error(String(response && response.status));
        await cache.put(href, response);
      } catch (err) {
        try {
          await cache.add(href);
        } catch (err2) {
          console.warn("PWA cache skip", path, err2);
        }
      }
    }));
  }
}

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    await cacheAll(cache);
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    const stored = await cache.keys();
    if (stored.length > 40) {
      const keys = await caches.keys();
      await Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)));
    }
    await self.clients.claim();
    const clients = await self.clients.matchAll({ includeUncontrolled: true });
    for (const client of clients) {
      client.postMessage({ type: "cached" });
    }
  })());
});

async function cachedResponse(request) {
  const cache = await caches.open(CACHE_NAME);
  const url = new URL(request.url);
  url.hash = "";
  const candidates = [request, url.href];
  if (url.pathname.endsWith("/")) {
    candidates.push(new URL("index.html", url.href).href);
  } else if (!/\.[a-z0-9]+$/i.test(url.pathname)) {
    candidates.push(url.href.replace(/\/?$/, "/") + "index.html");
  }
  for (const candidate of candidates) {
    const hit = await cache.match(candidate, { ignoreSearch: true });
    if (hit) return hit;
  }
  return undefined;
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET" || !inScope(request.url)) return;
  event.respondWith((async () => {
    const cached = await cachedResponse(request);
    if (cached) return cached;
    try {
      const fresh = await fetch(request);
      if (fresh && fresh.ok && inScope(request.url)) {
        const cache = await caches.open(CACHE_NAME);
        cache.put(request, fresh.clone());
      }
      return fresh;
    } catch (err) {
      if (request.mode === "navigate") {
        const offline = await cachedResponse(new Request(assetURL("offline.html")));
        if (offline) return offline;
        const home = await cachedResponse(new Request(assetURL("index.html")));
        if (home) return home;
      }
      throw err;
    }
  })());
});
